#!/bin/bash

echo "🔐 מדריך להוצאת LinkedIn Cookie - li_at"
echo "========================================"
echo ""
echo "📱 שלב 1: פתחי את LinkedIn בדפדפן"
echo "   - היכנסי לחשבון שלך ב-LinkedIn"
echo "   - ודאי שאת מחוברת"
echo ""
echo "🔧 שלב 2: פתחי את כלי המפתחים"
echo "   - לחצי F12 (או Cmd+Option+I במק)"
echo "   - או: קליק ימני > Inspect"
echo ""
echo "🍪 שלב 3: מצאי את ה-Cookie"
echo "   - לכי ללשונית: Application (או Storage)"
echo "   - בצד שמאל: Cookies > https://www.linkedin.com"
echo "   - חפשי: li_at"
echo ""
echo "📋 שלב 4: העתיקי את הערך"
echo "   - לחצי על li_at"
echo "   - העתיקי את כל הערך (מתחיל ב-AQE...)"
echo "   - זה יהיה ארוך מאוד - כ-400 תווים"
echo ""
echo "💾 שלב 5: הוסיפי ל-.env"
echo "   - פתחי את קובץ .env"
echo "   - הדביקי במקום הריק אחרי LINKEDIN_SESSION_COOKIE="
echo ""
echo "⚠️  חשוב:"
echo "   - ה-Cookie תקף ל-1 שנה"
echo "   - אל תשתפי אותו עם אף אחד"
echo "   - אם תתנתקי מ-LinkedIn, תצטרכי cookie חדש"
echo ""
echo "🎯 דוגמה:"
echo 'LINKEDIN_SESSION_COOKIE="AQEDAUl3....(400 תווים)....xyz"'
echo ""
echo "✅ אחרי שתוסיפי את ה-Cookie:"
echo "   1. npm install dotenv"
echo "   2. node check-api-keys.js"
echo "   3. python3 scripts/smart-integration-orchestrator.py" 